#### Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Import Dataset

In [2]:
# Import the dataset

iris_data = pd.read_csv('./iris.csv')

In [3]:
# Checking the dataset

iris_data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

#### Data Splitting using train_test_split method

In [4]:
# Import train_test_split library from scikit-learn

from sklearn.model_selection import train_test_split

In [5]:
# Separating the independent variables from dependent variables

x=iris_data.iloc[:,:-1]
y=iris_data.iloc[:,4]

x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.20)

#### Import SVM Library

In [6]:
# Import svm library from scikit-learn

from sklearn.svm import SVC

#### Import Libraries for classification and confusion matrix

In [7]:
# Importing the classification report and confusion matrix

from sklearn.metrics import classification_report, confusion_matrix

### Linear Kernel

#### Training support vector machine model with 'Linear' kernel

In [8]:
linear_model=SVC(kernel='linear')

linear_model.fit(x_train, y_train)

SVC(kernel='linear')

#### Predictions from the trained model ('Linear' kernel)

In [9]:
pred_linear = linear_model.predict(x_test)

#### Evaluation of 'Linear' kernel model

In [10]:
print(confusion_matrix(y_test,pred_linear))

[[11  0  0]
 [ 0  8  0]
 [ 0  0 11]]


In [11]:
print(classification_report(y_test, pred_linear))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



### Gaussian Kernel

#### Training support vector machine model with 'Gaussian' kernel

In [12]:
gaussian_model=SVC(kernel='rbf')

gaussian_model.fit(x_train, y_train)

SVC()

#### Predictions from the trained model ('Gaussian' kernel)

In [13]:
pred_gaussian = gaussian_model.predict(x_test)

#### Evaluation of 'Gaussian' kernel model

In [14]:
print(confusion_matrix(y_test,pred_gaussian))

[[11  0  0]
 [ 0  8  0]
 [ 0  2  9]]


In [15]:
print(classification_report(y_test, pred_gaussian))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.80      1.00      0.89         8
 Iris-virginica       1.00      0.82      0.90        11

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



### Polynomial Kernel

#### Training support vector machine model with 'Polynomial' kernel

In [16]:
polynomial_model=SVC(kernel='poly', degree=8)

polynomial_model.fit(x_train, y_train)

SVC(degree=8, kernel='poly')

#### Predictions from the trained model ('Polynomial' kernel)

In [17]:
pred_polynomial = polynomial_model.predict(x_test)

#### Evaluation of 'Polynomial' kernel model

In [18]:
print(confusion_matrix(y_test,pred_polynomial))

[[11  0  0]
 [ 0  8  0]
 [ 0  2  9]]


In [19]:
print(classification_report(y_test, pred_polynomial))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.80      1.00      0.89         8
 Iris-virginica       1.00      0.82      0.90        11

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



All of three kernels: Linear, Gaussian and Polynomial are performing well for this dataset. Between the three kernels, Linear kernel is performing the best. The best kernel for this dataset can't always be the best for all.